name: earthengine
channels:
        - conda-forge        
dependencies:
        - python=3.7.3
        - earthengine-api        
        - pydrive
        - pandas
        - numpy
        - scikit-image        